/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * oh admin
 * 一个非常优秀的中后台
 * OpenAPI spec version: 1.0
 */
import type { PasswordLoginDto } from './passwordLoginDto';
import type { EmailLoginDto } from './emailLoginDto';

export type AuthControllerLoginBody = PasswordLoginDto | EmailLoginDto;
