/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * oh admin
 * 一个非常优秀的中后台
 * OpenAPI spec version: 1.0
 */

export type AuthControllerCheckEmailParams = {
/**
 * 邮箱地址
 */
email: string;
};
