/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * oh admin
 * 一个非常优秀的中后台
 * OpenAPI spec version: 1.0
 */
import type { EmailLoginDtoLoginType } from './emailLoginDtoLoginType';

export interface EmailLoginDto {
  /** 登录类型 */
  loginType: EmailLoginDtoLoginType;
  /** 邮箱 */
  email: string;
  /** 验证码 */
  code: string;
}
