/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * oh admin
 * 一个非常优秀的中后台
 * OpenAPI spec version: 1.0
 */

export interface GetUserDto {
  id: number;
  email: string;
  /** @nullable */
  role?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  des?: string | null;
  /** @nullable */
  nickname?: string | null;
  /** @nullable */
  avatar?: string | null;
}
