/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * oh admin
 * 一个非常优秀的中后台
 * OpenAPI spec version: 1.0
 */
import type { PasswordLoginDtoLoginType } from './passwordLoginDtoLoginType';

export interface PasswordLoginDto {
  /** 登录类型 */
  loginType: PasswordLoginDtoLoginType;
  /** 账户（用户名或邮箱） */
  account: string;
  /** 密码 */
  password: string;
}
