/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * oh admin
 * 一个非常优秀的中后台
 * OpenAPI spec version: 1.0
 */

/**
 * 登录类型
 */
export type PasswordLoginDtoLoginType = typeof PasswordLoginDtoLoginType[keyof typeof PasswordLoginDtoLoginType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PasswordLoginDtoLoginType = {
  password: 'password',
} as const;
