/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * oh admin
 * 一个非常优秀的中后台
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /** 用户名 */
  username: string;
  /** 邮箱 */
  email: string;
  /** 验证码 */
  code: string;
  /** 密码 */
  password: string;
}
