/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * oh admin
 * 一个非常优秀的中后台
 * OpenAPI spec version: 1.0
 */

/**
 * 业务场景类型
 */
export type SendCodeDtoType = typeof SendCodeDtoType[keyof typeof SendCodeDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SendCodeDtoType = {
  login: 'login',
  register: 'register',
  forgot_password: 'forgot_password',
  change_email: 'change_email',
  change_phone: 'change_phone',
  sensitive_operation: 'sensitive_operation',
} as const;
