/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * oh admin
 * 一个非常优秀的中后台
 * OpenAPI spec version: 1.0
 */
import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const appControllerGetHello = (
    
 options?: SecondParameter<typeof customAxiosInstance<void>>,) => {
      return customAxiosInstance<void>(
      {url: `/`, method: 'GET'
    },
      options);
    }
  export type AppControllerGetHelloResult = NonNullable<Awaited<ReturnType<typeof appControllerGetHello>>>
