/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * oh admin
 * 一个非常优秀的中后台
 * OpenAPI spec version: 1.0
 */
import type {
  AuthControllerCheckEmailParams,
  AuthControllerCheckUsernameParams,
  AuthControllerLoginBody,
  ExistsResponseDto
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * 支持密码登录和邮箱验证码登录两种方式
 * @summary 用户登录
 */
export const authControllerLogin = (
    authControllerLoginBody: AuthControllerLoginBody,
 options?: SecondParameter<typeof customAxiosInstance<void>>,) => {
      return customAxiosInstance<void>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authControllerLoginBody
    },
      options);
    }
  /**
 * 用于注册时验证用户名是否已被使用
 * @summary 检查用户名是否存在
 */
export const authControllerCheckUsername = (
    params: AuthControllerCheckUsernameParams,
 options?: SecondParameter<typeof customAxiosInstance<ExistsResponseDto>>,) => {
      return customAxiosInstance<ExistsResponseDto>(
      {url: `/auth/check-username`, method: 'GET',
        params
    },
      options);
    }
  /**
 * 用于注册时验证邮箱是否已被注册
 * @summary 检查邮箱是否存在
 */
export const authControllerCheckEmail = (
    params: AuthControllerCheckEmailParams,
 options?: SecondParameter<typeof customAxiosInstance<ExistsResponseDto>>,) => {
      return customAxiosInstance<ExistsResponseDto>(
      {url: `/auth/check-email`, method: 'GET',
        params
    },
      options);
    }
  export type AuthControllerLoginResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
export type AuthControllerCheckUsernameResult = NonNullable<Awaited<ReturnType<typeof authControllerCheckUsername>>>
export type AuthControllerCheckEmailResult = NonNullable<Awaited<ReturnType<typeof authControllerCheckEmail>>>
