/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * oh admin
 * 一个非常优秀的中后台
 * OpenAPI spec version: 1.0
 */
import type {
  GetUserDto
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const userControllerGetUsers = (
    
 options?: SecondParameter<typeof customAxiosInstance<GetUserDto[]>>,) => {
      return customAxiosInstance<GetUserDto[]>(
      {url: `/user`, method: 'GET'
    },
      options);
    }
  export type UserControllerGetUsersResult = NonNullable<Awaited<ReturnType<typeof userControllerGetUsers>>>
