/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * oh admin
 * 一个非常优秀的中后台
 * OpenAPI spec version: 1.0
 */
import type {
  SendCodeDto
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * 向指定邮箱发送验证码，支持多种业务场景
 * @summary 发送验证码
 */
export const verificationControllerSendCode = (
    sendCodeDto: SendCodeDto,
 options?: SecondParameter<typeof customAxiosInstance<void>>,) => {
      return customAxiosInstance<void>(
      {url: `/verification/send`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendCodeDto
    },
      options);
    }
  export type VerificationControllerSendCodeResult = NonNullable<Awaited<ReturnType<typeof verificationControllerSendCode>>>
